### ISSUE TITLE
fly.ioデプロイしたアプリのエラーを直したい

### ISSUE THREAD

**Issue by kan0109** [kan0109/tirtumo#31]
**質問内容・実現したいこと**
fly.ioでデプロイは正常に完了したが、ユーザー登録ができないです。
データーベースが正常に接続されてないと思いました。
ログを確認したところ、

ERROR No such file or directory (os error 2)
2023-07-28T02:54:56Z app[9080e447b14018] nrt [info]I, [2023-07-28T02:54:56.523212 #255]  INFO -- : [cf82fd60-dc9b-4e95-892d-b23ad0f55e7b] Started GET "/users/new" for 66.241.124.117 at 2023-07-28 02:54:56 +0000
2023-07-28T02:54:56Z app[9080e447b14018] nrt [info]I, [2023-07-28T02:54:56.523918 #255]  INFO -- : [cf82fd60-dc9b-4e95-892d-b23ad0f55e7b] Processing by UsersController#new as HTML
2023-07-28T02:54:56Z app[9080e447b14018] nrt [info]I, [2023-07-28T02:54:56.527490 #255]  INFO -- : [cf82fd60-dc9b-4e95-892d-b23ad0f55e7b] Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.7ms | Allocations: 178)
2023-07-28T02:54:56Z app[9080e447b14018] nrt [info]F, [2023-07-28T02:54:56.527965 #255] FATAL -- : [cf82fd60-dc9b-4e95-892d-b23ad0f55e7b]
2023-07-28T02:54:56Z app[9080e447b14018] nrt [info][cf82fd60-dc9b-4e95-892d-b23ad0f55e7b] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2023-07-28T02:54:56Z app[9080e447b14018] nrt [info]LINE 9:  WHERE a.attrelid = '"users"'::regclass

下記のエラー内容がusersテーブルが存在しないというエラーが発生しています。
ローカル環境では、ユーザー登録などできているが、本番環境で上記のエラーが発生しました。

**どの処理までうまく動いているのか**

デプロイしてアプリを開くと、トップページは正常に表示されました。
下記の画像でデプロイは成功しています。
![image](https://github.com/kan0109/tirtumo/assets/114494047/c80c3f49-cb54-4823-a8a3-c49b4d51a77a)

![image](https://github.com/kan0109/tirtumo/assets/114494047/50c306ff-a2a9-4837-b569-e2f3540a3929)

**エラーから考えられる原因**

テーブルの問題ではなく、データーベースがうまく接続されていないと思ったんですが、具体的な原因はよくわからないです。

**試したこと**

下記の記事を参考にデプロイを進めました。
https://zenn.dev/hokawa/articles/65ddcd9974448c

また一度アプリを削除して、fly.toml、Dockerfile、.dockerignore、これらのファイルも削除し、fly launch からやり直したのですが、デプロイは成功し、ユーザー登録ができず、状態は変わりませんでした。

**Comment by Tsuchiya2** [comment]
まず本番環境のデータベースにアクセスできる状態になっているのか確認しましょう。
（https://github.com/kan0109/tirtumo/blob/main/config/database.yml にusernameとかpasswordを設定されているようですが、それを使ってアプリケーションはデータベースにアクセスできているかどうか）

次にアクセスできる状態になっていたら、マイグレーションファイルが適応されているか確認しましょう。（本番環境のデータベースに反映されているかという意味です）

マイグレーションファイルの適応も確認できたら、fiy.ioでrailsコンソールを立ち上げてuserが生成できるかどうか試してみましょう。

**Comment by kan0109** [comment]
早速のご返信ありがとうございます。
下記の通り、本番環境のデータベースにアクセスできました。
しかし、usersテーブルのレコードを取得してみてるとエラーが起き、レコードを習得することができませんでした。
RAILS_ENV=production bundle exec rails c
Loading production environment (Rails 7.0.5)
irb(main):001:0> User.all
An error occurred when inspecting the object: #<ActiveRecord::NoDatabaseError:"We could not find your database: tiritumo_development\". Which can be found in the database configuration file located at config/database.yml.\n\nTo resolve this issue:\n\n- Did you create the database for this app, or delete it? You may need to create your database.\n- Has the database name changed? Check your database.yml config has the correct database name.\n\nTo create your database, run:\n\n        bin/rails db:create\n">
Result of Kernel#inspect: #<User::ActiveRecord_Relation:0x0000000114522d20 @klass=User (call 'User.connection' to establish a connection), @table=#<Arel::Table:0x0000000115d274e8 @name="users", @klass=User (call 'User.connection' to establish a connection), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00000001144cbd40 @klass=User (call 'User.connection' to establish a connection)>, @table_alias=nil>, @values={}, @loaded=false, @predicate_builder=#<ActiveRecord::PredicateBuilder:0x00000001144cb638 @table=#<ActiveRecord::TableMetadata:0x00000001144cb7f0 @klass=User (call 'User.connection' to establish a connection), @arel_table=#<Arel::Table:0x0000000115d274e8 @name="users", @klass=User (call 'User.connection' to establish a connection), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00000001144cbd40 @klass=User (call 'User.connection' to establish a connection)>, @table_alias=nil>, @reflection=nil>, @handlers=[[Set, #<ActiveRecord::PredicateBuilder::ArrayHandler:0x00000001144c9c20 @predicate_builder=#<ActiveRecord::PredicateBuilder:0x00000001144cb638 ...>>], [Array, #<ActiveRecord::PredicateBuilder::ArrayHandler:0x00000001144c9dd8 @predicate_builder=#<ActiveRecord::PredicateBuilder:0x00000001144cb638 ...>>], [ActiveRecord::Relation, #<ActiveRecord::PredicateBuilder::RelationHandler:0x00000001144ca008>], [Range, #<ActiveRecord::PredicateBuilder::RangeHandler:0x00000001144ca8f0 @predicate_builder=#<ActiveRecord::PredicateBuilder:0x00000001144cb638 ...>>], [BasicObject, #<ActiveRecord::PredicateBuilder::BasicObjectHandler:0x00000001144cb200 @predicate_builder=#<ActiveRecord::PredicateBuilder:0x00000001144cb638 ...>>]]>, @delegate_to_klass=false, @future_result=nil, @records=nil, @should_eager_load=false, @arel=#<Arel::SelectManager:0x0000000113f9f858 @ast=#<Arel::Nodes::SelectStatement:0x0000000115d27498 @cores=[#<Arel::Nodes::SelectCore:0x00000001155a6ea8 @source=#<Arel::Nodes::JoinSource:0x0000000113f9e548 @left=#<Arel::Table:0x0000000115d274e8 @name="users", @klass=User (call 'User.connection' to establish a connection), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00000001144cbd40 @klass=User (call 'User.connection' to establish a connection)>, @table_alias=nil>, @right=[]>, @set_quantifier=nil, @optimizer_hints=nil, @projections=[#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x0000000115d274e8 @name="users", @klass=User (call 'User.connection' to establish a connection), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00000001144cbd40 @klass=User (call 'User.connection' to establish a connection)>, @table_alias=nil>, name="*">], @wheres=[], @groups=[], @havings=[], @windows=[], @comment=nil>], @orders=[], @limit=nil, @lock=nil, @offset=nil, @with=nil>, @ctx=#<Arel::Nodes::SelectCore:0x00000001155a6ea8 @source=#<Arel::Nodes::JoinSource:0x0000000113f9e548 @left=#<Arel::Table:0x0000000115d274e8 @name="users", @klass=User (call 'User.connection' to establish a connection), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00000001144cbd40 @klass=User (call 'User.connection' to establish a connection)>, @table_alias=nil>, @right=[]>, @set_quantifier=nil, @optimizer_hints=nil, @projections=[#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x0000000115d274e8 @name="users", @klass=User (call 'User.connection' to establish a connection), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00000001144cbd40 @klass=User (call 'User.connection' to establish a connection)>, @table_alias=nil>, name="*">], @wheres=[], @groups=[], @havings=[], @windows=[], @comment=nil>>>
=> 

エラーのログを調べてみると、データベース接続の問題が発生しており、tiritumoユーザーのユーザー名またはパスワードが正しくない可能性があると確認できました。
またconfig/database.yml、ここに記載されたコードが間違っていると思い、ActiveRecord::Base.connectionを使って、データベースに接続してみました。
config/database.yml

production:
  <<: *default
  database: tiritumo_development"
  username: postgres
  password: password


bundle exec rails c
Loading development environment (Rails 7.0.5)
irb(main):001:0> ActiveRecord::Base.connection
=> 
#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x0000000110652dc0
 @advisory_locks_enabled=true,
 **@config={:adapter=>"postgresql", :encoding=>"unicode", :pool=>5, :username=>"postgres", :password=>"password", :host=>"localhost", :database=>"tiritumo_development"},**
 @connection=#<PG::Connection:0x000000010eca4590 host=localhost port=5432 user=postgres type_map_for_results=#<PG::TypeMapByOid:0x000000010ee0ae20> type_map_for_queries=#<PG::TypeMapByClass:0x000000010ee435b8>>,
 @connection_parameters={:user=>"postgres", :password=>"password", :dbname=>"tiritumo_development", :host=>"localhost"},
 @default_timezone=:local,
 @idle_since=313724.351233,



configの情報を習得しました。
これにconfig/database.ymlの情報を合わせ見たのですが、usersテーブルのレコードは習得できませんでした。

**Comment by Tsuchiya2** [comment]
bundle exec rails c が実行しているのは開発環境ですよね。問題なのは本番環境との接続かと思うので、共有いただいた bundle exec rails c の部分はあまり参考にならないかもです。

RAILS_ENV=production bundle exec rails c のコマンドも本番環境用のコンソールをローカル上で立ち上げているかと思うので、本番環境上でrailsコンソールを立ち上げてみましょう。

参考：https://fly.io/docs/rails/the-basics/run-tasks-and-consoles/

**Comment by kan0109** [comment]
申し訳ございませんでした。
記事を参考にやってみたのですが、本番環境でrails cが立ち上がらなかったです。
下記のエラーが出てきました。
fly ssh console --pty -C "/rails/bin/rails console"
Connecting to fdaa:2:63e3:a7b:17b:acff:7792:2... complete
Error: ssh shell: wait: remote command exited without exit status or exit signal

https://teratail.com/questions/t7kjisz414de8f
同じエラーの記事を見つけたところ、メモリを上げたらできたと記載されていました。

**Comment by Tsuchiya2** [comment]
fly ssh console --pty -C "/rails/bin/rails console"

試したこととしては↑のコマンドを実行したのみということでしょうか。
「Interactive shell」のところにあるsetupのところは試されていますでしょうか。

**Comment by Tsuchiya2** [comment]
fly ssh console --pty -C "/rails/bin/rails console"

試したこととしては↑のコマンドを実行したのみということでしょうか。
「Interactive shell」のところにあるsetupのところは試されていますでしょうか。

**Comment by kan0109** [comment]
**Interactive shell」のところにあるsetupのところは試されていますでしょうか。**
試してなかったため試したところ、できました。


omikanta$ flyctl ssh add
Use SSH to login to or run commands on VMs

Usage:
  flyctl ssh [command]

Available Commands:
  console     Connect to a running instance of the current app.
  issue       Issue a new SSH credential
  log         Log of all issued SSH certs
  sftp        Get or put files from a remote VM.

Flags:
  -h, --help   help for ssh

Global Flags:
  -t, --access-token string   Fly API Access Token
      --verbose               Verbose output

Use "flyctl ssh [command] --help" for more information about a command.
oomihiroshinoMacBook-Air:tiritumo omikanta$ flyctl ssh console
Connecting to fdaa:2:63e3:a7b:17b:acff:7792:2... complete
root@32874ddda631e8:/rails# 



もう一度、fly ssh console --pty -C "/rails/bin/rails console"を試しましたが、エラーが起きました。

fly ssh console --pty -C "/rails/bin/rails console"
Connecting to fdaa:2:63e3:a7b:17d:164a:f3b5:2... complete
Loading production environment (Rails 7.0.5)
irb(main):001:0> Error: ssh shell: wait: remote command exited without exit status or exit signal

**Comment by Tsuchiya2** [comment]
sshでの接続もできて無さそうですね。
設定が出来ていないのか、ログイン状態に無いためか分かりませんが、公式ドキュメントにssh周りに言及されているものが無いか調べてみましょう。

https://fly.io/docs/rails/getting-started/dockerfiles/

↑の公式ドキュメントにメモリの上げ方があったので共有まで。

**Comment by kan0109** [comment]
頂いた記事を参考にメモリを上げたところ、fly ssh console --pty -C "/rails/bin/rails console"、こちらのコードは通りました。
![image](https://github.com/kan0109/tirtumo/assets/114494047/599754f6-9f45-4ca6-8a92-1858b82949a1)

また、ユーザーを作成したところ作成はされたんですが、追加で作成したところ、エラーが起きました。
データーベースの設定がうまくいってないと思いました。
ご確認のほどよろしくお願いいたします。
![image](https://github.com/kan0109/tirtumo/assets/114494047/d448ed42-4bbd-44f2-881d-6d998ac1975f)
![image](https://github.com/kan0109/tirtumo/assets/114494047/8d27077d-18e7-4945-889a-327f08498d06)
![image](https://github.com/kan0109/tirtumo/assets/114494047/f524ff68-6544-4829-85d0-4325d8df1fe2)

**Comment by kan0109** [comment]
もう一度fly launchから作り直し、fly deployした後に、下記のマイグレーションファイルを適用するコマンドをしたら、できました。
fly ssh console -C "bundle exec rails db:migrate"
マイグレーションファイルがうまく適用できていなかったのが問題だったみたいです。
土屋様ご教示いただきありがとうございました。
