### ISSUE TITLE
デプロイしたアプリに画像を貼り付けたいです

### ISSUE THREAD

**Issue by kan0109** [kan0109/tirtumo#32]
**質問内容・実現したいこと**
デプロイが完了した後に、投稿機能の画像とプロフィール編集の画像が貼り付けられないです。
投稿は画像無しだとエラーは発生しないです。
下記が、プロフィール編集したときのログでございます。
<img width="1439" alt="a410cf4f2b9b1d63e894951cf71d0d9b" src="https://github.com/kan0109/tirtumo/assets/114494047/3737e55e-ebda-4753-831a-a905c092f70c">

**試したこと**
Errno::EACCES (Permission denied @ dir_s_mkdir - /rails/public/uploads/tmp/1690897657-435690765052692-0001-9714):
このエラーが、アプリケーションに必要な権限が付与されていないため、アクセスが拒否されたというエラーでした。
下記の記事を参考に、fly ssh console、mkdir -p public/uploads/tmp、chmod -R 777 public/uploads/tmpを実行しましたが、同じエラーが発生している状態です。

https://teratail.com/questions/ieek9hin8f1272

**Comment by Tsuchiya2** [comment]
まず確認ですが、デプロイ先の情報（Heroku, fly.io, AWS, etc）が不足しているので憶測になりますがご了承ください。

/rails/public/uploads/tmp/配下に画像を保存したいということでしょうか？開発環境下ではpublic/配下に投稿された画像情報等を保管することがありますが、本番環境ではS3などに画像をアップロードすることが多いので、どこに画像を保存したいのか、保存先は適切なのか、保存先にアップロードする設定は適切になっているかetcを調べたり、検証してみてください。

**Comment by kan0109** [comment]
ご連絡遅くなりすいませんでした。
土屋さんのおっしゃる通り、本番環境でAWS s3を使い画像の保存先を作成したら問題も解決しました。
ご教授いただきありがとうございます。
