### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [kan0109/tirtumo#35]
@kan0109 
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## READMEから課題解決する実装がされているか&動いている
基本的に情報を登録する部分、情報を確認する部分ができていますね！
細かい点などレビューがありますが、通知機能など技術的にアピールポイントになる機能は本リリースまで実装しておいてください。

## 静的コードチェックが入っている
rubocopを導入してしっかりチェックしていますね。
これで最低限のコードの担保ができているので、引き続き静的コードチェックを続けていきましょう！

## 就活において十分な技術力を示せる機能を実装しているか
もう少し技術的にアピールになる機能がほしいので、LINEでの通知機能、もしくは登録されているデータを用いた節約情報&方法のレコメンド機能などを本リリースまでに実装しましょう。
### 高度な機能レコメンド
代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。
#### 使用技術・ライブラリ
* Amazon Personalize
    * https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
    * AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
* GCP Recommendations AI
    * https://cloud.google.com/recommendations?hl=ja
    * Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
* アルゴリズム
    * 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。

また下記に気になる点を記載したのでご確認ください。
- usersテーブルのtotal_savingsやlevelはカラムで情報をもつよりresultの情報を収集して計算するロジックで表示するのがいいですね、もしくはusersとは別のテーブルで情報管理するようにするのが良さそうです（total_savingsのためだけにusersテーブルを頻繁に更新したくない意図です）
- like周りのroutingはresourcesベースで作ってあげましょう。
- users_controllerのindex内での`@user = current_user`は利用していなさそうなので、削除しておきましょう。もし利用している場合はcurrent_userをそのまま利用するようにしましょう。
- targets_controllerのcreateアクションのsave部分はtarget_amountの更新と整合性を合わせるためにtransactionを利用しましょう。
- records_controllerがfat controllerになっているので、modelへのメソッドの切り出しをしておきましょう。（levelの分岐や更新処理はuserモデル、レベル別表示処理はdecorator、月のrecord取得処理はrecordsモデル、calculate_savingsはmy_pages_controllerと処理が被ってるのでmodelに切り出すなど）
- records_controllerのupdateアクションもtransactionで整合性を確保しましょう。
- posts_controllerのindexの分岐での情報取得はprivateメソッドに切り出しておきましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
下記に気になる点と機能強化できそうな部分を挙げたのでご確認ください。

- ヘッダーのメニューを整理しておきましょう、全ての導線へのページリンクをヘッダーに貼っていますが、種類ごとでまとめておくととても見やすくなります！（ユーザー情報系は右にまとめる、頻繁に利用する機能への導線のみヘッダーメニューに表示する）
- 目標設定画面は情報の有無をフォームで表すようにしましょう。
- 記録部分は1日1回かと思うので、記録している場合はフォームなしで登録情報だけ見えるように変えてあげましょう。
- ユーザー一覧ページがある意味合いが弱いので、ランクなどユーザーごとに異なる情報で探しやすいような機能も入れておきましょう。（ランク順で並び替え、週ごとの頑張っているユーザーランキングなど）
- ユーザー一覧の節約帳部分はカーソルのデザインを当てこむようにしてクリックできることが分かるようにしましょう。
- 記録の項目はデフォルトのものに加えて、ユーザーごとの独自項目設定が1,2つほど作れるようにしてもいいかもですね。（それが他ユーザーから見えて参考になったりするので）
- 投稿のメニューは新規と一覧だけにして、昇順降順などの並び替えは一覧ページ内に導線を作るようにしましょう。
- 投稿一覧の情報はタグなどを準備して、種類別で情報が見えるように検索しやすい仕組みを取り入れましょう。
- コツコツ節約した情報がグラフなどで可視化できると、過去の頑張りも見えていいかもです。

UI系は下記のサイトがとても参考になるのでぜひ見てもらえるとです！
https://www.sociomedia.co.jp/category/uidesignpatterns

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by kan0109** [comment]
レビューいただきありがとうございます。
自分自身気づかないことが多く、貴重なレビューをいただき大変感謝しています。
いただいた問題点をもとにissueを作成いたしました。
issueをもとに本リリースまでのスケジュールは8月25日にを目標に本リリースをしたいと思っております。

**Comment by kerochelo** [comment]
@kan0109 
承知しました！もう引き続き実装を進めてさらに良いサービスを作っていきましょう！
